sentence_level1 = [
"Sorry 죄송합니다 [jesonghamnida]",
"The game will be paused for a moment 게임 잠시 중단됩니다 [Game jamsi jungdan demnida]",
"I will proceed again after verifying this 확인 후, 다시 진행하겠습니다 [hwagin hu, dasi jinhaeng hagetseumnida]",
"I am waiting for assistance 도움을 기다리고 있습니다 [doumeul gidarigo itsseum nida]",
"Thank you for waiting so long 오래 기다려 주셔서 감사합니다 [orae gidaryeo jusyeoseo gamsahamnida]",
"The game is starting again 게임 다시 시작합니다 [Game dasi sijakamnida]",
"Hello dear Players 플레이어 여러분 안녕하세요 [Player yeoreobun annyeonghaseyo]",
"I am dealer OO your for this session 이번 세션을 맡은 딜러 OO입니다 [ibeon sessioneul mateun dealer (your name) imnida]",
"I am dealer OO your for this session 이번 세션을 맡은 딜러 OO입니다 [ibeon session dealer (your name) imnida]",
"It’s time to place your bets 베팅 시간입니다 [betting sigan imnida]",
"Betting time is open 베팅 시간 오픈 되었습니다 [betting sigan open de eot sseumnida ]",
"The new round is open 새 라운드가 오픈되었습니다 [sae round-ga open de eot seumnida]",
"The new round is open 새로운 라운드가 오픈되었습니다 [saeroun round-ga open de eot seumnida]",
"Everyone, lt’s time to place your bets 여러분, 베팅 할 시간입니다 [yeoreobun, betting hal sigan imnida]",
"Please place your bets 베팅해 주세요 [betting hae juseyo]",
"Betting time has closed 배팅 시간 마감했습니다 [betting sigan magam haetseumnida]",
"Betting is closed, and the game is about to begin 베팅 마감하고 게임 시작합니다 [betting magamhago game sijakamnida]",
"Wishing you good luck 행운을 빌어요 [haenguneul bireoyo]",
"Betting is closed, and good luck 베팅 마감하고 행운을 빌어요 [betting magamhago haenguneul bireoyo]",
"I will deal the card to the player 플레이어 카드 드리겠습니다 [player card deuriget seumnida]",
"I will deal the card to the banker 뱅커 카드 드리겠습니다 [banker card deuriget seumnida]",
"Player receives an extra card, then 플레이어 추가 카드 받고 [player chuga card bad ggo]", 
"banker receives an extra card, then 뱅커 추가 카드 받고 [banker chuga card bad ggo]",   
"banker wins with a natural 8 뱅커 네추럴 8로 승리합니다 [baker natural pal ro seungnihamnida]", 
"player wins with a natural 8 플레이어 네추럴 8로 승리합니다 [baker natural pal ro seungnihamnida]",
"banker wins with a natural 9 뱅커 네추럴 9로 승리합니다 [baker natural gu ro seungnihamnida]", 
"player wins with a natural 9 플레이어 네추럴 9로 승리합니다 [baker natural gu ro seungnihamnida]",
"Congratulations to the winners 승리하신 분들 축하드립니다 [seungnihasin bundeul chukadeurimnida]"
]
